### ISSUE TITLE
Error de SSL al intentar loguearme con Mercado Libre

### ISSUE THREAD

**Issue by hernandezed** [sdurandeu/passport-mercadolibre#2]
Estoy intentando hacer el login contra mercado libre, pero estoy teniendo problemas con los protocolos, node no posee sslv3 por default, por lo cual no estoy pudiendo solucionar esto.

Vi que en la documentacion al final nombran esto, pero no estoy encontrando forma de o habilitar ssl3 (lo cual no me interesa por las vulnerabilidades) o hacerlo entrar por otro protocolo.

Desconosco si esto es un issue o no, por lo que me gustaria saber esto para en caso de no serlo buscar ayuda por otros lados.

desde ya muchisimas gracias!

**Comment by feliperoberto** [comment]
Could you check if PR https://github.com/sdurandeu/passport-mercadolibre/pull/3 solve your problem?
